/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_cuda_CuMatrix */

#ifndef _Included_jni_cuda_CuMatrix
#define _Included_jni_cuda_CuMatrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_cuda_CuMatrix
 * Method:    destruct
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jni_cuda_CuMatrix_destruct
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jni_cuda_CuMatrix
 * Method:    init
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_jni_cuda_CuMatrix_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jni_cuda_CuMatrix
 * Method:    add
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jni_cuda_CuMatrix_add
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     jni_cuda_CuMatrix
 * Method:    addDouble
 * Signature: (JD)J
 */
JNIEXPORT jlong JNICALL Java_jni_cuda_CuMatrix_addDouble
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     jni_cuda_CuMatrix
 * Method:    pow
 * Signature: (JD)J
 */
JNIEXPORT jlong JNICALL Java_jni_cuda_CuMatrix_pow
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     jni_cuda_CuMatrix
 * Method:    sqrt
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jni_cuda_CuMatrix_sqrt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jni_cuda_CuMatrix
 * Method:    sum
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jni_cuda_CuMatrix_sum
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
